### ISSUE TITLE
invalid json response body

### ISSUE THREAD

**Issue by codingwithdidem** [makeswift/makeswift#107]
Hello I followed the docs and tried both manual & getting started guides but can't figure out the below problem. 

I put my API_KEY in env file btw 

<img width="1232" alt="Screen Shot 2022-07-02 at 12 22 51" src="https://user-images.githubusercontent.com/78794523/176994606-eeeb99c4-73e8-4b5e-9359-4d61c9ed64f2.png">

**Comment by migueloller** [comment]
@codingwithdidem, @joshuawootonn is looking into this and working on much better error messages so please stay tuned! 😄

**Comment by migueloller** [comment]
@codingwithdidem, #121 should fix this issue! Please let me know if you run into it again 😄
