### ISSUE TITLE
Next 13 Support - Cannot read properties of undefined (reading 'and')

### ISSUE THREAD

**Issue by TylerAHolden** [makeswift/makeswift#305]
It appears that next-transpile-modules needs to be updated to 10.0 for [this line](https://github.com/martpie/next-transpile-modules/blob/master/src/next-transpile-modules.js#L210). Although the repo is now archived and says: "All features of next-transpile-modules are now natively built-in Next.js 13.1. Please use Next's transpilePackages option :)"

**Comment by fikrikarim** [comment]
Hey @TylerAHolden, we just released [a new version](https://github.com/makeswift/makeswift/releases/tag/%40makeswift%2Fruntime%400.5.0) that supports Next 13.

You can use it by upgrading `@makeswift/runtime` to version `0.5.0` in `package.json`.

Please let us know if you run into any more issues!
