### ISSUE TITLE
Makeswift's thirdweb template Github Repo showing blank page after deployed in Vercel

### ISSUE THREAD

**Issue by admLabs7** [makeswift/makeswift#448]
https://github.com/makeswift/makeswift/tree/main/examples/thirdweb?ref=blog.thirdweb.com

We have followed steps from [README.md](https://github.com/makeswift/makeswift/tree/main/examples/thirdweb?ref=blog.thirdweb.com#readme)
After clicking on deploy to Vercel , deployment done successfully but page is loading blank with error - 404 Page could not be found error

**Comment by migueloller** [comment]
@admLabs7, have you gone into your Makeswift site and published the page?

**Comment by warengonzaga** [comment]
Remove any site from your Makeswift dashboard, then try again adding that from Vercel. @admLabs7

**Comment by admLabs7** [comment]
It worked after removing all old sites and re deployment. thank you !

**Comment by Royalnft** [comment]
I  cant see the claim botton .the phases is fine.
