### ISSUE TITLE
Integrations

### ISSUE THREAD

**Issue by ridhopurba** [makeswift/makeswift#631]
![Screenshot 2023-12-06 234808](https://github.com/makeswift/makeswift/assets/153100597/97f49887-290e-40db-aa40-c21e148bbfa0)
Adding makeswift integrations to vercel takes forever to load and never finish.

**Comment by ridhopurba** [comment]
![image](https://github.com/makeswift/makeswift/assets/153100597/7abab185-c811-4bda-b621-0fbd8f44ca9c)
Still not fixed only getting worse

**Comment by migueloller** [comment]
Hey @ridhopurba, this should be fixed now, do you mind trying again?
