### ISSUE TITLE
What file types are supported during upload?

### ISSUE THREAD

**Issue by paulbuskovskij** [makeswift/makeswift#652]
Recently, I've been encountering the following error when attempting to upload files:

`{
    "errors": [
        {
            "message": "Validation failed",
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "path": [
                "uploadFiles"
            ],
            "extensions": {
                "code": "BAD_REQUEST",
                "originalError": {
                    "statusCode": 400,
                    "message": "Validation failed",
                    "errors": [
                        {
                            "code": "invalid_type",
                            "expected": "object",
                            "received": "null",
                            "path": [
                                "input",
                                "data",
                                "files",
                                0,
                                "dimensions"
                            ],
                            "message": "Expected object, received null"
                        }
                    ]
                }
            }
        }
    ],
    "data": null
}
`

**Comment by migueloller** [comment]
@paulbuskovskij, sorry to hear you're running into that issue. Which version of the runtime are you on?

**Comment by migueloller** [comment]
Also, can you share a bit more about the file you're attempting to upload? It seems that it's missing dimensions so perhaps there is our bug in our system measuring this specific file.

**Comment by paulbuskovskij** [comment]
@migueloller I am trying to upload .ics file as I have created a calendar module which accesses this type of files. Where can I check the version of the runtime?

**Comment by migueloller** [comment]
Ok, this seems like a problem on our end. Looking at the error you shared above, there seems to be an expectation that dimensions are included but dimensions are only present in media files, like images. A .ics file doesn't have any dimensions. We're looking into it.

**Comment by paulbuskovskij** [comment]
Any news?

**Comment by migueloller** [comment]
Hey @paulbuskovskij, I've got a fix going out right now! Will keep you posted.

**Comment by migueloller** [comment]
Ok, you should now be able to upload .ics files!
