### ISSUE TITLE
App router page loads perfectly but then on rehydration page is loaded from scratch

### ISSUE THREAD

**Issue by arifullahjan** [makeswift/makeswift#796]
### Describe the bug

First of all, thank you for this awesome solution. I am still on the free plan 🙈 but we are an early-stage startup and I do my part in promoting it among my friends 😅. 

I have been noticing this after I implemented the app router integration.

### Steps to reproduce

**Steps:**
1. Go to https://jobr.pro in incognito (or disable cache from network)
2. Notice the page loads perfectly with all styles applied but suddenly it disappears and causes layout shift

**Expected Behavior:**
No layout shift

**Actual Behavior:**
There is a huge layout shift

### Screenshots/Videos

https://github.com/makeswift/makeswift/assets/20574210/fd934b37-8278-4d1d-9d79-ee1295d5e4c1

### Environment

 - Makeswift Runtime version: `0.19.1`

**Comment by migueloller** [comment]
Hi @arifullahjan,

I'm glad you're liking Makeswift! And I'm sorry that you're running into this issue.

Would it be able to get a repo with a minimal reproduction? From what I'm seeing it seems that the HTML response has all the content there but once React hydrates the content disappears and then comes back. I'd like to figure out if this is a bug with `0.19.1` of the runtime or an issue with your Makeswift integration.

Regardless of what the problem is I'd like to help here and a repo with a reproduction would go a long way!

**Comment by fikrikarim** [comment]
Hi @arifullahjan,

Two things I noticed on the website:
1. The flicker/layout shift only happens on the main content of the page, and it doesn't happen on the navigation or on the footer. I'm guessing you have a layout with a hardcoded navigation and footer that only renders the `Page` from Makeswift inside that layout?
2. I noticed some React errors. Have you tried reproducing the issue locally on development? I wonder if the problem would be solved once we address all the React errors here.
<img width="841" alt="image" src="https://github.com/makeswift/makeswift/assets/13066728/95f909b5-64e3-4748-a49d-330cc8da01f2">
Or sometimes it's only this error:
<img width="713" alt="image" src="https://github.com/makeswift/makeswift/assets/13066728/efc26989-cdfe-47c0-8313-ccd7e06f1ddf">



I agree with Miguel that it'd be perfect if you could provide a minimal reproduction of the issue so we can debug it.

**Comment by arifullahjan** [comment]
Thanks for your response. I will do that

**Comment by arifullahjan** [comment]
@fikrikarim Thanks for the suggestion. I ignored the hydration failed errors causing the whole tree to remount. It was too dumb of me 😃 . The issue was in the header (I use custom one) because of HTML structure check in nextjs and happened throughout my app causing request duplication.

Sorry for the inconvenience

**Comment by fikrikarim** [comment]
@arifullahjan Glad to hear that. We want to support a lot of use cases, so we want to help as we can. Let us know if you have any other issues/questions!
